### ISSUE TITLE
Traduction Champ de force brun (brown force field) manquante

### ISSUE THREAD

**Issue by Tsht** [aldarion-jdr/sfrpg-fr-translation#15]
Il manque une traduction de champ de force. On a : blanc, bleu, gris, noir, orange, pourpre, prismatique, rouge, vert mais il manque le brun (brown).
On trouve bien "force field, brown" en cherchant dans le compendium.

**Comment by ArtheniusRPG** [comment]
ca sera bon pour la prochaine MAJ ;) merci
