### ISSUE TITLE
Gestion des états

### ISSUE THREAD

**Issue by Faelwen** [aldarion-jdr/sfrpg-fr-translation#21]
Bonjour,

J'ai remarqué quelques problèmes au niveau de la gestion des états qui ne se produisent pas dans la version anglaise.

Par exemple, dans la version anglaise, sans aucun module chargé, voici ce que j'observe :
- Activer un état depuis un token répercute cet état dans la feuille de personnage et vice-versa.
- Activer un état ajoute automatiquement le trait associé dans la feuille de personnage avec ses effets. Ainsi, si l'on active l'effet "Prone" (à terre), cela va automatiquement appliquer un malus de 4 aux attaques de mêlée). 

En revanche, si j'active la version française (module de traduction + babele), voici le comportement que j'observe :
- Activer un état depuis un token ne répercute pas cet état dans la feuille de personnage. En revanche, activer un état depuis la feuille de personnage le répercute sur le token. Du coup, il est possible d'activer deux fois le même effet sur un token.
- Activer un état n'ajoute pas automatiquement le trait dans la feuille de personnage. Les modificateurs ne sont donc pas appliqués. Si j'active l'effet "A terre", cela n'active pas le malus de 4 sur les attaques de mêlée.

Je vous remercie au passage pour le gros travail que vous apporté sur ce projet.

Cordialement,

**Comment by aldarion-jdr** [comment]
Hello !
Après plusieurs tentatives je confirme que nous ne pouvons rien faire de notre côté.
Le système de base utilise les noms VO et ça plante tout une fois traduit.
Je leur ai signalé, je ne sais pas ce qui sera fait pour remédier à ce problème ni quand.
Pas de ticket ouvert chez eux, en discussion sur le Discord et en fonction de leur réponse il faudra le signaler sur leur GIT.
